#网站基本设置
场所: "en-US"
标题: “你的姓名/网址”
描述: “个人说明”
统一资源定位系统: "https://academicpages.github.io"  #替换为你的实际网站 URL
baseurl: ""  # 如果你的网站有子路径，请填写，否则保持为空
仓库: "yourusername/yourrepository"  #替换为你的 GitHub

#设置默认的首页布局为无
违约:
  - 范围:
路径: ""  # 匹配所有文件
类型: 页# 匹配所有页面
值:
布局: 没有一个# 不使用任何布局

# 设置主页的路径
永久: /index.html

# 其他配置可以根据需要保留或修改
# ...
